image: debian/sid
packages:
- gcc-aarch64-linux-gnu
- qemu-user
sources:
- https://git.sr.ht/~mcf/cproc
- https://git.sr.ht/~mcf/qbe
tasks:
- build: |
    PATH=$HOME/qbe/obj:$PATH
    cd qbe
    cat >config.h <<EOF
    #define Defasm Gaself
    #define Deftgt T_arm64
    EOF
    make
    cd ../cproc
    ./configure \
      --target=aarch64-linux-gnu \
      --with-ldso=/usr/aarch64-linux-gnu/lib/ld-linux-aarch64.so.1 \
      --with-gcc-libdir=/usr/lib/gcc-cross/aarch64-linux-gnu/8
    make all check
    make bootstrap LDFLAGS='-Wl,-rpath,/usr/aarch64-linux-gnu/lib'
    file stage2/cproc stage2/cproc-qbe
triggers:
- action: email
  condition: failure
  to: ~mcf/cproc@lists.sr.ht
