image: openbsd/latest
sources:
- https://git.sr.ht/~mcf/cproc
- git://c9x.me/qbe.git
packages:
- gmake
environment:
  PATH: $HOME/qbe/obj:$PATH
tasks:
- setup: |
    # avoid __asm__ on non __GNUC__ compilers
    doas patch -d /usr/include/amd64 < cproc/.builds/openbsd.diff
- build: |
    gmake -C qbe
    cd cproc
    ./configure
    make all check bootstrap
triggers:
- action: email
  condition: failure
  to: ~mcf/cproc@lists.sr.ht
